docs_dir: docs/book
site_dir: docs/html
extra:
  project: Components
  current_version: v3
  versions:
    - v3
    - v2
    - v1
nav:
  - Home: index.md
  - v3:
    - Overview: v3/overview.md
    - Installation: v3/install.md
    - Usage: v3/usage.md
    - Reference:
      - Factories: v3/factories.md
      - "Server Request Filters": v3/server-request-filters.md
      - "Custom Responses": v3/custom-responses.md
      - Serialization: v3/serialization.md
      - API: v3/api.md
    - Migration:
      - "Migration to Version 3": v3/migration.md
  - v2:
    - Overview: v2/overview.md
    - Installation: v2/install.md
    - Usage: v2/usage.md
    - Reference:
      - Factories: v2/factories.md
      - "Server Request Filters": v2/server-request-filters.md
      - "Custom Responses": v2/custom-responses.md
      - Serialization: v2/serialization.md
      - API: v2/api.md
    - Migration:
      - "Migration to Version 2": v2/migration.md
      - "Preparing for Version 3": v2/forward-migration.md
  - v1:
    - Overview: v1/overview.md
    - Installation: v1/install.md
    - Usage: v1/usage.md
    - Reference:
      - "Custom Responses": v1/custom-responses.md
      - "Emitting Responses": v1/emitting-responses.md
      - Serialization: v1/serialization.md
      - API: v1/api.md
site_name: laminas-diactoros
site_description: "PSR-7 HTTP message implementations"
repo_url: "https://github.com/laminas/laminas-diactoros"
plugins:
  - search
  - redirects:
      redirect_maps:
        overview.md: v3/overview.md
        install.md: v3/install.md
        usage.md: v3/usage.md
        custom-responses.md: v3/custom-responses.md
        emitting-responses.md: v1/emitting-responses.md
        serialization.md: v3/serialization.md
        api.md: v3/api.md
